//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int id { get; set; }
        public Nullable<int> Orderid { get; set; }
        public Nullable<int> Serviceid { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Zakazy Zakazy { get; set; }
        public virtual Serivce Serivce { get; set; }
    }
}
